import Link from "next/link";
import { redirect } from "next/navigation";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";
import { resolveCompany } from "@/lib/ai/resolver";
import { Hero } from "@/components/brief/hero";
import { friendlyError } from "@/components/brief/section-card";
import { WhatCard } from "@/components/brief/what-card";
import { FoundersCard } from "@/components/brief/founders-card";
import { NewsCard } from "@/components/brief/news-card";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  try {
    const company = await resolveCompany(decodeURIComponent(slug));
    return {
      title: `${company.name} — Diliq`,
      description: `Investment brief on ${company.name}.`,
    };
  } catch {
    return { title: "Company — Diliq" };
  }
}

function PageShell({ children }: { children: React.ReactNode }) {
  return (
    <main className="relative min-h-screen overflow-hidden px-6 py-10">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 -top-40 -z-10 h-[36rem] opacity-70 blur-3xl"
        style={{
          background:
            "radial-gradient(ellipse 60% 50% at 20% 0%, rgba(139,92,246,0.18), transparent 70%), radial-gradient(ellipse 50% 50% at 80% 10%, rgba(34,211,238,0.12), transparent 70%)",
        }}
      />
      <div className="relative mx-auto max-w-5xl">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-white/45 transition hover:text-white/90"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back
        </Link>
        {children}
      </div>
    </main>
  );
}

export default async function CompanyPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug: rawSlug } = await params;
  const requested = decodeURIComponent(rawSlug);

  let company;
  try {
    company = await resolveCompany(requested);
  } catch (err) {
    const raw = err instanceof Error ? err.message : String(err);
    const { headline, detail } = friendlyError(raw);
    return (
      <PageShell>
        <div className="mt-12 rounded-2xl border border-amber-300/15 bg-amber-300/[0.04] p-8">
          <p className="text-xs font-medium uppercase tracking-[0.2em] text-amber-200/80">
            Couldn&apos;t load brief
          </p>
          <p className="mt-3 text-2xl font-medium tracking-tight text-white">
            {headline}
          </p>
          {detail && (
            <p className="mt-2 text-sm text-white/60">{detail}</p>
          )}
          <p className="mt-6 font-mono text-xs text-white/30">
            Requested slug: {requested}
          </p>
        </div>
      </PageShell>
    );
  }

  if (company.slug !== requested) {
    redirect(`/c/${company.slug}`);
  }

  return (
    <PageShell>
      <div className="mt-8">
        <Hero company={company} />
      </div>

      <section className="mt-10 grid gap-5">
        <WhatCard slug={company.slug} />
        <FoundersCard slug={company.slug} />
        <NewsCard slug={company.slug} />
      </section>

      <footer className="mt-16 border-t border-white/[0.06] pt-6 text-center text-xs text-white/30">
        Generated by Claude with web search · cited where possible · always
        verify facts before acting
      </footer>
    </PageShell>
  );
}
